### ISSUE TITLE
How to send it to new contacts not present in recent chats?

### ISSUE THREAD

**Issue by debadridtt** [harshitsidhwa/WhatsApp-bot-selenium#1]
Hey,

I have some new contacts, whom I haven't sent anything before so they are not appearing on the feed. But for this program, it is able to detect people who are present on the feed and not the contacts. So how do I change that thing?

**Comment by harshitsidhwa** [comment]
You have to search the contact person name or person phone number in the search input and then search.. wait for some time, till the search result appears.
