### ISSUE TITLE
Error: No module named selenium. details: 

### ISSUE THREAD

**Issue by XKMR** [harshitsidhwa/WhatsApp-bot-selenium#13]
Message=No module named 'selenium'
  Source=C:\Users\kamya\OneDrive\Desktop\sw\WhatsApp-bot-selenium-master\whatsapp.py
  StackTrace:
  File "C:\Users\kamya\OneDrive\Desktop\sw\WhatsApp-bot-selenium-master\whatsapp.py", line 6, in <module> (Current frame)
    from selenium import webdriver

**Comment by ghost** [comment]
Dude just install selenium first
```pip install selenium```

**Comment by XKMR** [comment]
I already did that
