### ISSUE TITLE
How to send a message who is not in the contact list?

### ISSUE THREAD

**Issue by suthakarkb** [harshitsidhwa/WhatsApp-bot-selenium#2]
How to send a message who is not in the contact list?

In Web Whatsapp, Now we can send message whose number not in our contact list, Extra page appears with message button. Is it possible to modify this program to do that.

**Comment by harshitsidhwa** [comment]
Can't do.
The contact needs to be in your contact list, or in recent chat or maybe in Archive Chats.
Regarding the web WhatsApp what your saying, I didn't get, can you please elaborate more, or steps to replicate the scenario.

**Comment by suthakarkb** [comment]
Hi Harshitsidhwa

   Thanks for your reply.
   There is a option in web whatsapp to send message to the user whose name
is not in our contact list
   URL :   https://wa.me/919578725571, Click "message" button, Type
<<Message>>, Click Send
   If we have 5 dirrerent contact numbers in excel sheet as below
   919578725571
   919578725572
   919578725573
   919578725574
   919578725575

   Then selenium app should invoke the URLs as below.
   https://wa.me/919578725571
   https://wa.me/919578725572
   https://wa.me/919578725573
   https://wa.me/919578725574
   https://wa.me/919578725575

  Then selenium need to click a "message" button and need to type the
configured message and send.

Thanks

**Comment by harshitsidhwa** [comment]
Ohh. That way..
What your saying is correct, but here the thing is Selenium uses a kind of
incognito browser mode of chrome/firefox etc.
Hence one needs to login again and again.
So what one can do is.
Open web whatsApp using the selenium
Process the excel sheet, create the URL's : https://wa.me/91
<https://wa.me/919578725571>xxxxxxxxxx
Open these url in a new Tab (not new instance of the browser)
And then click on the send Message button..
Rest is same process.

Selenium provides option to open link in the new tab, and switch between
them, so it makes easy to handle the messages.

**Comment by suthakarkb** [comment]
Hi Harshitsidhwa,

   Thanks for your detailed reply.

**Comment by pengyanbing84** [comment]
If the name is not in the recent chat history, the name cannot be searched from the WhatsApp contact list and sent，Is it solved?
